// components/booking/data.ts
import { Booking } from "./types"

export const bookings: Booking[] = [
  {
    id: "BK-001",
    patient: "Budi Santoso",
    phone: "081234567890",
    email: "budi@example.com",
    location: "Cabang Jakarta",
    therapist: "Andi (Bonesetting)",
    datetime: "2025-02-20T09:00",
    paymentStatus: "Lunas",
    description: "Keluhan pada tulang belakang",
  },
  {
    id: "BK-002",
    patient: "Siti Rahma",
    phone: "081298765432",
    email: "siti@example.com",
    location: "Cabang Bandung",
    therapist: "Budi (Fisioterapi)",
    datetime: "2025-02-20T10:00",
    paymentStatus: "Belum Lunas",
    description: "Terapi bahu kanan",
  },
  {
    id: "BK-003",
    patient: "Ahmad Fauzi",
    phone: "081234112233",
    email: "ahmad@example.com",
    location: "Cabang Jakarta",
    therapist: "Sari (Terapi Saraf)",
    datetime: "2025-02-20T11:00",
    paymentStatus: "Lunas",
    description: "Terapi leher",
  },
  {
    id: "BK-004",
    patient: "Dewi Lestari",
    phone: "081299887766",
    email: "dewi@example.com",
    location: "Cabang Surabaya",
    therapist: "Andi (Bonesetting)",
    datetime: "2025-02-20T13:00",
    paymentStatus: "Belum Lunas",
    description: "Terapi pinggang",
  },
  {
    id: "BK-005",
    patient: "Rizky Pratama",
    phone: "081277788899",
    email: "rizky@example.com",
    location: "Cabang Jakarta",
    therapist: "Budi (Fisioterapi)",
    datetime: "2025-02-20T14:00",
    paymentStatus: "DP",
    description: "Terapi lutut",
  },
  {
    id: "BK-006",
    patient: "Nina Kurnia",
    phone: "081233344455",
    email: "nina@example.com",
    location: "Cabang Bandung",
    therapist: "Budi (Fisioterapi)",
    datetime: "2025-02-20T15:00",
    paymentStatus: "Lunas",
    description: "Terapi bahu kiri",
  },
  {
    id: "BK-007",
    patient: "Andi Wijaya",
    phone: "081255566677",
    email: "andi@example.com",
    location: "Cabang Surabaya",
    therapist: "Sari (Terapi Saraf)",
    datetime: "2025-02-21T09:00",
    paymentStatus: "Belum Lunas",
    description: "Terapi leher",
  },
  {
    id: "BK-008",
    patient: "Putri Ayu",
    phone: "081244433322",
    email: "putri@example.com",
    location: "Cabang Jakarta",
    therapist: "Andi (Bonesetting)",
    datetime: "2025-02-21T10:00",
    paymentStatus: "Lunas",
    description: "Keluhan tulang belakang",
  },
  {
    id: "BK-009",
    patient: "Yoga Saputra",
    phone: "081266677788",
    email: "yoga@example.com",
    location: "Cabang Bandung",
    therapist: "Sari (Terapi Saraf)",
    datetime: "2025-02-21T11:00",
    paymentStatus: "Lunas",
    description: "Terapi pinggang",
  },
  {
    id: "BK-010",
    patient: "Linda Sari",
    phone: "081211122233",
    email: "linda@example.com",
    location: "Cabang Surabaya",
    therapist: "Budi (Fisioterapi)",
    datetime: "2025-02-21T13:00",
    paymentStatus: "Belum Lunas",
    description: "Terapi lutut",
  },
]
